version: "3.5"
services:
  php-fpm:
    depends_on:
      - db

  db:
    hostname: "${WARDEN_ENV_NAME}-mariadb"
    image: ${WARDEN_IMAGE_REPOSITORY}/${DB_DISTRIBUTION}:${DB_DISTRIBUTION_VERSION}}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-app}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-app}
      - MYSQL_USER=${MYSQL_USER:-app}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-app}
      - MYSQL_HISTFILE=/sql_history/.sql_history
    volumes:
      - dbdata:/var/lib/mysql
      - sqlhistory:/sql_history

volumes:
  dbdata:
  sqlhistory:
